name: Deploy Docker Web

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop old container
        shell: pwsh
        run: |
          Write-Host "Buscando contenedor existente..."
          $exists = docker ps -a --format "{{.Names}}" | Select-String -Pattern "^miweb$"
          if ($exists) {
            Write-Host "Contenedor encontrado. Eliminando..."
            docker stop miweb
            docker rm miweb
          } else {
            Write-Host "No existe contenedor previo."
          }

      - name: Build and Deploy
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
