name: Deploy Docker Web

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop old container
        shell: pwsh
        run: |
          Write-Host "Eliminando contenedor viejo si existe..."
          try {
            docker rm -f miweb -ErrorAction SilentlyContinue
          } catch {
            Write-Host "No hab√≠a contenedor viejo."
          }

      - name: Build and Deploy
        shell: pwsh
        run: |
          docker compose build --no-cache
          docker compose up -d
